### ISSUE TITLE
Improve UX to clarify what happens if user does not have profile pic

### ISSUE THREAD

**Issue by serena-zhu** [serena-zhu/Matcha#107]
Suggestions:

-add message on default profile picture to warn user that they cannot like or chat without a user profile page
-direct user to profile page instead of main matches page if they do not have a profile page

**Comment by jchung05** [comment]
Fixed, please check whether this meets spec and close if it does or pass it back

**Comment by serena-zhu** [comment]
done, closing

**Comment by serena-zhu** [comment]
users without a profile picture is not routed to profile page on sign in
