### ISSUE TITLE
First time users cannot access profile page due to Online/Offline check

### ISSUE THREAD

**Issue by jchung05** [serena-zhu/Matcha#110]
A user registering for the first time cannot go to the profile page due to the way online check is done since that is calculated backend. A first time user does not have a logout_time to compare against a login_time, so Werkzeug is throwing an error that will crash a user. Please refactor the way online/offline is handled

![bug](https://user-images.githubusercontent.com/4443041/40231214-0eadb8b6-5a4f-11e8-849a-3b46089b541d.png)
![bug2](https://user-images.githubusercontent.com/4443041/40231225-1d170218-5a4f-11e8-9d21-99c74b346e94.png)

**Comment by jchung05** [comment]
Fixed, please verify it works and close it out as the creator of this component

**Comment by serena-zhu** [comment]
Works, closing.
