### ISSUE TITLE
Make a verification email component for valid emails

### ISSUE THREAD

**Issue by jchung05** [serena-zhu/Matcha#116]
Specs state we **do** in fact need to validate emails with a hashed verification link before a user can use the site. Let's design a component that can be toggled on and off with requiring verification email such that testing and grading for other users isn't tedious.

**Comment by serena-zhu** [comment]
Need to implement on settings page as well for when users change their email.

**Comment by serena-zhu** [comment]
Added a config variable "ACCOUNT_ACTIVATION" in dev.py: set to True to turn on email verification, set to False to turn off the requirement. Will close issue after adding this process to settings page for changing email.

**Comment by serena-zhu** [comment]
done, closing
