### ISSUE TITLE
Perform site security vulnerability assessment before release

### ISSUE THREAD

**Issue by jchung05** [serena-zhu/Matcha#117]
We need to validate against common attacks. Certain things have been protected against such as: 
* XSS
* XSRF

We need to do validation against overflows and (D)DoS still before site release. Any common attacks per spec that succeed result in a failure for the project

**Comment by serena-zhu** [comment]
set up flask-limiter with config variables for number of requests per day or per minute. currently only implemented for /register route for testing. Need to discuss limits and implementation. Also, flask-limiter does not seem to work for post only routes from AJAX calls.

**Comment by serena-zhu** [comment]
Flask limiter works for AJAX post requests - just need to redirect with window.location to "/429" route when response status is 429.

**Comment by jchung05** [comment]
Post requests are not protected and can be spoofed for information not necessary to a specific user ID.

Polling unsafely checks for notification counts of any passed user_id and should be fixed since no JSON variable is needed to validate this.

Chat can be DDoS'd by a bot spamming messages. For some reason Flask Limiter does not limit the number of websocket messages sent and needs to be addressed.

Since chat boxes are loaded by passing the user IDs that are rendered in HTML, any user ID can be passed to generate a chat box that isn't valid for the user to access.

Will create 4 issues based off of this.

**Comment by jchung05** [comment]
Will reopen if issues are found in user testing
