### ISSUE TITLE
Impose correct request limits on routes and AJAX

### ISSUE THREAD

**Issue by jchung05** [serena-zhu/Matcha#126]
Routes will be handled via Flask Limiter, but AJAX may need another implementation, such as _throttle()

**Comment by serena-zhu** [comment]
259621456849dd34aceb6982126f225e3cee0d26

added default_limits in app/__init__.py for all routes. need to check AJAX response codes for 429 and redirect as needed.

**Comment by serena-zhu** [comment]
Per discussion, decided to use flask-limiter's default-limits for all routes and render 429.html as needed. Did not implement additional throttle or debounce functions with javascript.
