### ISSUE TITLE
Sterilize user input fields

### ISSUE THREAD

**Issue by serena-zhu** [serena-zhu/Matcha#14]
Sterilize user input fields in registration form e.g. only allow letters for first name, last name, etc. 

Also let users know what format is acceptable.

**Comment by jchung05** [comment]
People who write biographies over 250 characters throw an error.

**Comment by jchung05** [comment]
a73a558ac6e87a162deaa9a6b08c6051361beb7c

Biography field increased to 1000 characters max.

First/Last names only allow characters and spaces and require {3,20} characters.

Passwords are validated.

Age now has a max age such that no number overflows occur.

**Comment by jchung05** [comment]
c67bcddfb40d3b19009e2cba556fbf4dbd8cf869

Position increased to 50 characters max.
