### ISSUE TITLE
True Location

### ISSUE THREAD

**Issue by jchung05** [serena-zhu/Matcha#38]
User based lat and long are done but true location still needs to be determined somehow

**Comment by jchung05** [comment]
https://ipstack.com/
commercial use

http://ip-api.com/docs/api:json
non-commercial use for ip geolocation request

**Comment by serena-zhu** [comment]
Issue: User A does not have a specified location can still visit other users such as User B. When User B visits User A, there is no cached ratings value for user A. Need to check for a rating before routing user B to user A's profile and add it to cache if it does not exist.

**Comment by serena-zhu** [comment]
Per our discussion, User B will see "N/A" as User A's rating since providing a rating may disclose clues to User A's true location. 

Implemented and closing.
