### ISSUE TITLE
Create Search Forms w/ CSRF disabled

### ISSUE THREAD

**Issue by jchung05** [serena-zhu/Matcha#5]
https://media.readthedocs.org/pdf/flask-wtf/v0.12/flask-wtf.pdf

WTForms default establish CSRF tokens to prevent XSRF tokens. When we make the search functionality we should disable CSRF so searches can come from outside the site. Should we consider this or leave the CSRF tokens valid such that only people registered can search profiles within the site?

**Comment by serena-zhu** [comment]
Let's leave CSRF tokens valid to give users more privacy.
