### ISSUE TITLE
Flask errors file dump into all websocket chats

### ISSUE THREAD

**Issue by jchung05** [serena-zhu/Matcha#66]
Whenever Flask has a websocket handshake with users and the site crashes, all the information related to a debugging message gets dumped into a user's chatbox.

<img width="931" alt="screen shot 2018-05-12 at 5 47 25 am" src="https://user-images.githubusercontent.com/4443041/39957452-29504270-55a8-11e8-838f-b9a400e3cd0c.png">

**Comment by jchung05** [comment]
This issue is tied directly to how #62 is resolved. Depending on table implementation, the reference to each User object in the Jinja template will need to be handled differently.

The current change pushed to development requires one reference the user.User object whereas the previous one requires only the user object, since only one query object was held by it.

**Comment by serena-zhu** [comment]
Closing based on #62.
