### ISSUE TITLE
Distinguish sender from recipient messages

### ISSUE THREAD

**Issue by jchung05** [serena-zhu/Matcha#73]
Currently chats only display text with no context of sender and recipient. Some thoughts and suggestions:

Include names
Left and right side based on sender/recipient
Timestamps

**Comment by serena-zhu** [comment]
Sent messages are now pushed to the right while received messages are shown on the left. Per our discussion, we will append message id to each message so that on hover we can send AJAX request to get time stamp and display to user.

**Comment by serena-zhu** [comment]
After further discussion, rather than sending an AJAX request each time a user hovers over a message to get the time stamp, the time will be loaded with messages with one AJAX call. The div with the time stamp remains hidden until a user hovers over the message. Closing.
